### ISSUE TITLE
Convert video inputs to single frames

### ISSUE THREAD

**Issue by iremustek** [Asami-1/GDP#13]
Convert video inputs from custom data -> single frames so that we can give them directly to ViTPose

**Comment by quent1fvr** [comment]
Hi, this file contains a script equivalent to the one of Ivan :) 

For a given folder which contains videos files, this script extract each videos into frames and store it in a new specified folder. 

I think, we are done with this issue @iremustek :) 

[vid_to_frame.py.zip](https://github.com/Asami-1/GDP/files/10765988/vid_to_frame.py.zip)

**Comment by iremustek** [comment]
thanks guys! would you mind creating a new folder in the repository, "python scripts", and adding your zip file (any of them as both are working) to that folder
