### ISSUE TITLE
Run a small-demo on ViTPose (Depends on #13) & make-sure ViTPose runs properly

### ISSUE THREAD

**Issue by iremustek** [Asami-1/GDP#16]
(After #13)

**Comment by iremustek** [comment]
@quent1fvr is having problems with dependencies in the libraries etc. to use ViTPose. Will send it to @iremustek to try it

**Comment by quent1fvr** [comment]
@iremustek  I'm not able to upload the vitpose folder (too big). Do you have any suggestion?

Otherwise for now, I have just tried to follow the Vitpose github code provided 
https://github.com/ViTAE-Transformer/ViTPose in the section "Usage"
