### ISSUE TITLE
Preparing the slides for  16th presentation

### ISSUE THREAD

**Issue by Asami-1** [Asami-1/GDP#2]
Make slides for first presentation. They shall include the following points : 

1. Introduction (@jaygdesai )
2. Use case definition with papers and datasets (Keep it simple) (@quent1fvr , @sandhyakasthuri ,  @jjaiyang )
3. Team Role Breakdown (@jaygdesai )
4. Project management strategy : Agile, tools used... (@Asami-1 , @iremustek  )
5. Project plan (using officetimeline.com for example) ( @IviX55 )

**Comment by iremustek** [comment]
The template for the presentation is uploaded to [Teams](https://cranfield.sharepoint.com/:p:/r/sites/GDP-Group118-UGT-SATM/Shared%20Documents/General/Presentations/16.01.2023-Presentation-Template.pptx?d=wcf6f966c83ae4ab7bc8f20bcdb392503&csf=1&web=1&e=a0p7EX)

**Comment by jaygdesai** [comment]
> Make slides for first presentation. They shall include the following points :
> 
> 1. Introduction (@jaygdesai )
> 2. Use case definition with papers and datasets (Keep it simple) (@quent1fvr , @sandhyakasthuri ,  @jjaiyang )
> 3. Team Role Breakdown (@jaygdesai )
> 4. Project management strategy : Agile, tools used... (@Asami-1 , @iremustek  )
> 5. Project plan (using officetimeline.com for example) ( @IviX55 )

Completed slides for #1 and #3 above

**Comment by iremustek** [comment]
All slides are well prepared, and the presentation is over.
