### ISSUE TITLE
Making a user friendly script to refine IDs and label the video

### ISSUE THREAD

**Issue by Asami-1** [Asami-1/GDP#23]
Those scripts are to be applied on a copy of the main folder/
make a script so that each video is launched : 

* Script to visualize video

def visualize_video(path_to_raw_video, path_to_folder_with_json) : 

- Creation of the video with the bboxes and ids
- Displaying of the video in 15fps
- Display the frame number
-  if json has class display it
- Ask to visualize again
- If no :  Deletion of the video

* Script to delete track IDs

def remove_id(path_to_raw_video,path_to_folder_with_json):

- visualize_video
- Asks for IDs to be deleted
- Update every json accordingly
- visualize_video

* Script to merge track Ids

def merge_id(path_to_raw_video,path_to_folder_with_json):

- visualize_video
- Iterate over each ID :
   Ask each ID to merge with
   Update each json accordingly
   visualize_video

def label_video(path_to_raw_video,path_to_folder_with_json):

- Assign neutral class to every person in each json
- visualize_video
- Iterate over each ID :
   Is the person agressive/victim ? If yes, ask for intervals. Intervals should multiple of 2. One track id is either agressive or victim in one video
   Update each json accordingly, 
   visualize_video

* create an aux json to keep track of which video has been annotated

**Comment by iremustek** [comment]
Done. All data generated by DeepSort is manually labeled by using the Scripts in this Drive link: https://drive.google.com/drive/folders/1_J2fbve7XYZvuZgSJ2JJEhFWGxL98Fzt?usp=sharing
